version: "3.6"
services:
  app:
    build: "./app"
    ports:
      - "8090"
    depends_on:
      - "postgres"
      - "redis"
  web:
    build: "./web"
    ports:
      - "80:80"
      - "84:84"
    depends_on:
      - "app"
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
  redis:
    image: "redis:alpine"
    ports:
      - "6379"