version: "3.6"
services:
  app:
    build: "./app"
    ports:
      - "8090"
#    depends_on:
#      - "db"
  web:
    build: "./web"
    ports:
      - "80:80"
      - "84:84"
    depends_on:
      - "app"
#  db:
#    image: "postgres"
#    env_file:
#      - .secrets.env
#    ports:
#      - "5432"