// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package template

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TemplateClient is the client API for Template service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplateClient interface {
	GetKrHandler(ctx context.Context, in *GetKrHandlerRequest, opts ...grpc.CallOption) (*GetKrHandlerResponse, error)
	ApproveKrHandler(ctx context.Context, in *ApproveKrHandlerRequest, opts ...grpc.CallOption) (*ApproveKrHandlerResponse, error)
}

type templateClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplateClient(cc grpc.ClientConnInterface) TemplateClient {
	return &templateClient{cc}
}

func (c *templateClient) GetKrHandler(ctx context.Context, in *GetKrHandlerRequest, opts ...grpc.CallOption) (*GetKrHandlerResponse, error) {
	out := new(GetKrHandlerResponse)
	err := c.cc.Invoke(ctx, "/template.Template/GetKrHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateClient) ApproveKrHandler(ctx context.Context, in *ApproveKrHandlerRequest, opts ...grpc.CallOption) (*ApproveKrHandlerResponse, error) {
	out := new(ApproveKrHandlerResponse)
	err := c.cc.Invoke(ctx, "/template.Template/ApproveKrHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateServer is the server API for Template service.
// All implementations must embed UnimplementedTemplateServer
// for forward compatibility
type TemplateServer interface {
	GetKrHandler(context.Context, *GetKrHandlerRequest) (*GetKrHandlerResponse, error)
	ApproveKrHandler(context.Context, *ApproveKrHandlerRequest) (*ApproveKrHandlerResponse, error)
	mustEmbedUnimplementedTemplateServer()
}

// UnimplementedTemplateServer must be embedded to have forward compatible implementations.
type UnimplementedTemplateServer struct {
}

func (UnimplementedTemplateServer) GetKrHandler(context.Context, *GetKrHandlerRequest) (*GetKrHandlerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKrHandler not implemented")
}
func (UnimplementedTemplateServer) ApproveKrHandler(context.Context, *ApproveKrHandlerRequest) (*ApproveKrHandlerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveKrHandler not implemented")
}
func (UnimplementedTemplateServer) mustEmbedUnimplementedTemplateServer() {}

// UnsafeTemplateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplateServer will
// result in compilation errors.
type UnsafeTemplateServer interface {
	mustEmbedUnimplementedTemplateServer()
}

func RegisterTemplateServer(s grpc.ServiceRegistrar, srv TemplateServer) {
	s.RegisterService(&Template_ServiceDesc, srv)
}

func _Template_GetKrHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKrHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).GetKrHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template.Template/GetKrHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).GetKrHandler(ctx, req.(*GetKrHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Template_ApproveKrHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveKrHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).ApproveKrHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template.Template/ApproveKrHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).ApproveKrHandler(ctx, req.(*ApproveKrHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Template_ServiceDesc is the grpc.ServiceDesc for Template service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Template_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "template.Template",
	HandlerType: (*TemplateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKrHandler",
			Handler:    _Template_GetKrHandler_Handler,
		},
		{
			MethodName: "ApproveKrHandler",
			Handler:    _Template_ApproveKrHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/template/template.proto",
}
