// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package template

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	GetKrHandler(ctx context.Context, in *GetKrRequest, opts ...grpc.CallOption) (*OkMessage, error)
	ApproveKrHandler(ctx context.Context, in *GetKrRequest, opts ...grpc.CallOption) (*OkMessage, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) GetKrHandler(ctx context.Context, in *GetKrRequest, opts ...grpc.CallOption) (*OkMessage, error) {
	out := new(OkMessage)
	err := c.cc.Invoke(ctx, "/template.Auth/GetKrHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ApproveKrHandler(ctx context.Context, in *GetKrRequest, opts ...grpc.CallOption) (*OkMessage, error) {
	out := new(OkMessage)
	err := c.cc.Invoke(ctx, "/template.Auth/ApproveKrHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility
type AuthServer interface {
	GetKrHandler(context.Context, *GetKrRequest) (*OkMessage, error)
	ApproveKrHandler(context.Context, *GetKrRequest) (*OkMessage, error)
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (UnimplementedAuthServer) GetKrHandler(context.Context, *GetKrRequest) (*OkMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKrHandler not implemented")
}
func (UnimplementedAuthServer) ApproveKrHandler(context.Context, *GetKrRequest) (*OkMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveKrHandler not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_GetKrHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetKrHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template.Auth/GetKrHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetKrHandler(ctx, req.(*GetKrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ApproveKrHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ApproveKrHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template.Auth/ApproveKrHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ApproveKrHandler(ctx, req.(*GetKrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "template.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKrHandler",
			Handler:    _Auth_GetKrHandler_Handler,
		},
		{
			MethodName: "ApproveKrHandler",
			Handler:    _Auth_ApproveKrHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/template/template.proto",
}
