// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: proto/calculations/calculations.proto

/*
Package calculations is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package calculations

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_Calculations_DirectCodeLeftShiftCalculation_0(ctx context.Context, marshaler runtime.Marshaler, client CalculationsClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DirectCodeLeftShiftRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.DirectCodeLeftShiftCalculation(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_Calculations_DirectCodeLeftShiftCalculation_0(ctx context.Context, marshaler runtime.Marshaler, server CalculationsServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DirectCodeLeftShiftRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.DirectCodeLeftShiftCalculation(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterCalculationsHandlerServer registers the http handlers for service Calculations to "mux".
// UnaryRPC     :call CalculationsServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterCalculationsHandlerFromEndpoint instead.
func RegisterCalculationsHandlerServer(ctx context.Context, mux *runtime.ServeMux, server CalculationsServer) error {

	mux.Handle("POST", pattern_Calculations_DirectCodeLeftShiftCalculation_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/calculations.Calculations/DirectCodeLeftShiftCalculation", runtime.WithHTTPPathPattern("/api/v1/calculations/direct_code/left_shift"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_Calculations_DirectCodeLeftShiftCalculation_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_Calculations_DirectCodeLeftShiftCalculation_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterCalculationsHandlerFromEndpoint is same as RegisterCalculationsHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterCalculationsHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterCalculationsHandler(ctx, mux, conn)
}

// RegisterCalculationsHandler registers the http handlers for service Calculations to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterCalculationsHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterCalculationsHandlerClient(ctx, mux, NewCalculationsClient(conn))
}

// RegisterCalculationsHandlerClient registers the http handlers for service Calculations
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "CalculationsClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "CalculationsClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "CalculationsClient" to call the correct interceptors.
func RegisterCalculationsHandlerClient(ctx context.Context, mux *runtime.ServeMux, client CalculationsClient) error {

	mux.Handle("POST", pattern_Calculations_DirectCodeLeftShiftCalculation_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/calculations.Calculations/DirectCodeLeftShiftCalculation", runtime.WithHTTPPathPattern("/api/v1/calculations/direct_code/left_shift"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_Calculations_DirectCodeLeftShiftCalculation_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_Calculations_DirectCodeLeftShiftCalculation_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_Calculations_DirectCodeLeftShiftCalculation_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4}, []string{"api", "v1", "calculations", "direct_code", "left_shift"}, ""))
)

var (
	forward_Calculations_DirectCodeLeftShiftCalculation_0 = runtime.ForwardResponseMessage
)
