// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/calculations/calculations.proto

package calculations

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DirectCodeLeftShiftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Multiplier string `protobuf:"bytes,1,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	Factor     string `protobuf:"bytes,2,opt,name=factor,proto3" json:"factor,omitempty"`
}

func (x *DirectCodeLeftShiftRequest) Reset() {
	*x = DirectCodeLeftShiftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculations_calculations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectCodeLeftShiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectCodeLeftShiftRequest) ProtoMessage() {}

func (x *DirectCodeLeftShiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculations_calculations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectCodeLeftShiftRequest.ProtoReflect.Descriptor instead.
func (*DirectCodeLeftShiftRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculations_calculations_proto_rawDescGZIP(), []int{0}
}

func (x *DirectCodeLeftShiftRequest) GetMultiplier() string {
	if x != nil {
		return x.Multiplier
	}
	return ""
}

func (x *DirectCodeLeftShiftRequest) GetFactor() string {
	if x != nil {
		return x.Factor
	}
	return ""
}

type DirectCodeLeftShiftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sequence []*DirectCodeLeftShiftResponse_Step `protobuf:"bytes,1,rep,name=Sequence,proto3" json:"Sequence,omitempty"`
}

func (x *DirectCodeLeftShiftResponse) Reset() {
	*x = DirectCodeLeftShiftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculations_calculations_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectCodeLeftShiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectCodeLeftShiftResponse) ProtoMessage() {}

func (x *DirectCodeLeftShiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculations_calculations_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectCodeLeftShiftResponse.ProtoReflect.Descriptor instead.
func (*DirectCodeLeftShiftResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculations_calculations_proto_rawDescGZIP(), []int{1}
}

func (x *DirectCodeLeftShiftResponse) GetSequence() []*DirectCodeLeftShiftResponse_Step {
	if x != nil {
		return x.Sequence
	}
	return nil
}

type DirectCodeRightShiftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Multiplier string `protobuf:"bytes,1,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	Factor     string `protobuf:"bytes,2,opt,name=factor,proto3" json:"factor,omitempty"`
}

func (x *DirectCodeRightShiftRequest) Reset() {
	*x = DirectCodeRightShiftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculations_calculations_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectCodeRightShiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectCodeRightShiftRequest) ProtoMessage() {}

func (x *DirectCodeRightShiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculations_calculations_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectCodeRightShiftRequest.ProtoReflect.Descriptor instead.
func (*DirectCodeRightShiftRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculations_calculations_proto_rawDescGZIP(), []int{2}
}

func (x *DirectCodeRightShiftRequest) GetMultiplier() string {
	if x != nil {
		return x.Multiplier
	}
	return ""
}

func (x *DirectCodeRightShiftRequest) GetFactor() string {
	if x != nil {
		return x.Factor
	}
	return ""
}

type DirectCodeRightShiftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sequence []*DirectCodeRightShiftResponse_Step `protobuf:"bytes,1,rep,name=Sequence,proto3" json:"Sequence,omitempty"`
}

func (x *DirectCodeRightShiftResponse) Reset() {
	*x = DirectCodeRightShiftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculations_calculations_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectCodeRightShiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectCodeRightShiftResponse) ProtoMessage() {}

func (x *DirectCodeRightShiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculations_calculations_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectCodeRightShiftResponse.ProtoReflect.Descriptor instead.
func (*DirectCodeRightShiftResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculations_calculations_proto_rawDescGZIP(), []int{3}
}

func (x *DirectCodeRightShiftResponse) GetSequence() []*DirectCodeRightShiftResponse_Step {
	if x != nil {
		return x.Sequence
	}
	return nil
}

type DirectCodeLeftShiftResponse_Step struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index  uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	BinDec string `protobuf:"bytes,2,opt,name=bin_dec,json=binDec,proto3" json:"bin_dec,omitempty"`
	Value  string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DirectCodeLeftShiftResponse_Step) Reset() {
	*x = DirectCodeLeftShiftResponse_Step{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculations_calculations_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectCodeLeftShiftResponse_Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectCodeLeftShiftResponse_Step) ProtoMessage() {}

func (x *DirectCodeLeftShiftResponse_Step) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculations_calculations_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectCodeLeftShiftResponse_Step.ProtoReflect.Descriptor instead.
func (*DirectCodeLeftShiftResponse_Step) Descriptor() ([]byte, []int) {
	return file_proto_calculations_calculations_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DirectCodeLeftShiftResponse_Step) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DirectCodeLeftShiftResponse_Step) GetBinDec() string {
	if x != nil {
		return x.BinDec
	}
	return ""
}

func (x *DirectCodeLeftShiftResponse_Step) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DirectCodeRightShiftResponse_Step struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index  uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	BinDec string `protobuf:"bytes,2,opt,name=bin_dec,json=binDec,proto3" json:"bin_dec,omitempty"`
	Value  string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DirectCodeRightShiftResponse_Step) Reset() {
	*x = DirectCodeRightShiftResponse_Step{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculations_calculations_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectCodeRightShiftResponse_Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectCodeRightShiftResponse_Step) ProtoMessage() {}

func (x *DirectCodeRightShiftResponse_Step) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculations_calculations_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectCodeRightShiftResponse_Step.ProtoReflect.Descriptor instead.
func (*DirectCodeRightShiftResponse_Step) Descriptor() ([]byte, []int) {
	return file_proto_calculations_calculations_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DirectCodeRightShiftResponse_Step) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DirectCodeRightShiftResponse_Step) GetBinDec() string {
	if x != nil {
		return x.BinDec
	}
	return ""
}

func (x *DirectCodeRightShiftResponse_Step) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proto_calculations_calculations_proto protoreflect.FileDescriptor

var file_proto_calculations_calculations_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x1a, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x4c, 0x65, 0x66, 0x74, 0x53, 0x68, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0xb6, 0x01, 0x0a, 0x1b, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x4c, 0x65, 0x66, 0x74, 0x53, 0x68, 0x69, 0x66,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x08, 0x53, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x4c, 0x65, 0x66, 0x74, 0x53, 0x68, 0x69, 0x66, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x52, 0x08, 0x53, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x1a, 0x4b, 0x0a, 0x04, 0x53, 0x74, 0x65, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x69, 0x6e, 0x5f, 0x64, 0x65, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x44, 0x65, 0x63, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x55, 0x0a, 0x1b, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x69, 0x67, 0x68, 0x74, 0x53, 0x68, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0xb8, 0x01, 0x0a, 0x1c, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x69, 0x67, 0x68, 0x74, 0x53, 0x68, 0x69,
	0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x08, 0x53, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x69, 0x67, 0x68, 0x74, 0x53, 0x68, 0x69, 0x66, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x52, 0x08, 0x53,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x1a, 0x4b, 0x0a, 0x04, 0x53, 0x74, 0x65, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x69, 0x6e, 0x5f, 0x64, 0x65, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x44, 0x65, 0x63, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x32, 0xf2, 0x02, 0x0a, 0x0c, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0xad, 0x01, 0x0a, 0x1e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x4c, 0x65, 0x66, 0x74, 0x53, 0x68, 0x69, 0x66, 0x74, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x4c, 0x65, 0x66, 0x74, 0x53, 0x68, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x4c, 0x65, 0x66, 0x74,
	0x53, 0x68, 0x69, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x36, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x30, 0x22, 0x2b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x73, 0x68, 0x69,
	0x66, 0x74, 0x3a, 0x01, 0x2a, 0x12, 0xb1, 0x01, 0x0a, 0x1f, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x69, 0x67, 0x68, 0x74, 0x53, 0x68, 0x69, 0x66, 0x74, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x2e, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x69, 0x67, 0x68, 0x74, 0x53, 0x68, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x69,
	0x67, 0x68, 0x74, 0x53, 0x68, 0x69, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x37, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x31, 0x22, 0x2c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x72, 0x69, 0x67, 0x68, 0x74,
	0x5f, 0x73, 0x68, 0x69, 0x66, 0x74, 0x3a, 0x01, 0x2a, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x45, 0x6c, 0x64, 0x65, 0x72, 0x6c, 0x79, 0x2d,
	0x41, 0x49, 0x2f, 0x74, 0x61, 0x5f, 0x65, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3b, 0x63, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_calculations_calculations_proto_rawDescOnce sync.Once
	file_proto_calculations_calculations_proto_rawDescData = file_proto_calculations_calculations_proto_rawDesc
)

func file_proto_calculations_calculations_proto_rawDescGZIP() []byte {
	file_proto_calculations_calculations_proto_rawDescOnce.Do(func() {
		file_proto_calculations_calculations_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_calculations_calculations_proto_rawDescData)
	})
	return file_proto_calculations_calculations_proto_rawDescData
}

var file_proto_calculations_calculations_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_calculations_calculations_proto_goTypes = []interface{}{
	(*DirectCodeLeftShiftRequest)(nil),        // 0: calculations.DirectCodeLeftShiftRequest
	(*DirectCodeLeftShiftResponse)(nil),       // 1: calculations.DirectCodeLeftShiftResponse
	(*DirectCodeRightShiftRequest)(nil),       // 2: calculations.DirectCodeRightShiftRequest
	(*DirectCodeRightShiftResponse)(nil),      // 3: calculations.DirectCodeRightShiftResponse
	(*DirectCodeLeftShiftResponse_Step)(nil),  // 4: calculations.DirectCodeLeftShiftResponse.Step
	(*DirectCodeRightShiftResponse_Step)(nil), // 5: calculations.DirectCodeRightShiftResponse.Step
}
var file_proto_calculations_calculations_proto_depIdxs = []int32{
	4, // 0: calculations.DirectCodeLeftShiftResponse.Sequence:type_name -> calculations.DirectCodeLeftShiftResponse.Step
	5, // 1: calculations.DirectCodeRightShiftResponse.Sequence:type_name -> calculations.DirectCodeRightShiftResponse.Step
	0, // 2: calculations.Calculations.DirectCodeLeftShiftCalculation:input_type -> calculations.DirectCodeLeftShiftRequest
	2, // 3: calculations.Calculations.DirectCodeRightShiftCalculation:input_type -> calculations.DirectCodeRightShiftRequest
	1, // 4: calculations.Calculations.DirectCodeLeftShiftCalculation:output_type -> calculations.DirectCodeLeftShiftResponse
	3, // 5: calculations.Calculations.DirectCodeRightShiftCalculation:output_type -> calculations.DirectCodeRightShiftResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_calculations_calculations_proto_init() }
func file_proto_calculations_calculations_proto_init() {
	if File_proto_calculations_calculations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_calculations_calculations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirectCodeLeftShiftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculations_calculations_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirectCodeLeftShiftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculations_calculations_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirectCodeRightShiftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculations_calculations_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirectCodeRightShiftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculations_calculations_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirectCodeLeftShiftResponse_Step); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculations_calculations_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirectCodeRightShiftResponse_Step); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_calculations_calculations_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calculations_calculations_proto_goTypes,
		DependencyIndexes: file_proto_calculations_calculations_proto_depIdxs,
		MessageInfos:      file_proto_calculations_calculations_proto_msgTypes,
	}.Build()
	File_proto_calculations_calculations_proto = out.File
	file_proto_calculations_calculations_proto_rawDesc = nil
	file_proto_calculations_calculations_proto_goTypes = nil
	file_proto_calculations_calculations_proto_depIdxs = nil
}
